"""Command line interface."""

import io
from typing import Literal

import click
import json5
from pydantic import BaseModel

from .templates import render


class Column(BaseModel):
    name: str
    type: str


class Table(BaseModel):
    name: str
    columns: list[Column]
    column_type: Literal["vector"]
    with_sort: bool = False
    with_par_for_each: bool = False
    with_par_sort: bool = False
    csv_reader_type: str | None = None
    csv_writer_type: str | None = None


class CodeSpec(BaseModel):
    namespace: str
    tables: list[Table]


def write_table(fobj: io.TextIOWrapper, table: Table):
    if table.column_type == "vector":
        struct_str = render("vector:vector", table=table)
        fobj.write(struct_str)
        fobj.write("\n\n")

    if table.csv_reader_type is not None:
        class_str = render(
            "arrow:csv_reader", reader_type=table.csv_reader_type, table=table
        )
        fobj.write(class_str)
        fobj.write("\n\n")

    if table.csv_writer_type is not None:
        class_str = render(
            "arrow:csv_writer", writer_type=table.csv_writer_type, table=table
        )
        fobj.write(class_str)
        fobj.write("\n\n")


@click.command()
@click.option(
    "-i",
    "--input",
    "input_file",
    type=click.Path(exists=True, file_okay=True, dir_okay=False),
    required=True,
    help="Input file",
)
@click.option(
    "-o",
    "--output",
    "output_file",
    type=click.Path(exists=False, file_okay=True, dir_okay=False),
    required=True,
    help="Output file",
)
def cli(input_file: str, output_file: str):
    """Struct of array generator."""
    spec: CodeSpec
    with open(input_file, "rt") as fobj:
        spec = CodeSpec.model_validate(json5.load(fobj))

    headers = ["cstdint"]

    def add_header(header):
        if header not in headers:
            headers.append(header)

    for table in spec.tables:
        if table.column_type == "vector":
            add_header("vector")

        if table.with_sort:
            add_header("algorithm")

        if table.with_par_for_each:
            add_header("taskflow/taskflow.hpp")
            add_header("taskflow/algorithm/for_each.hpp")

        if table.with_par_sort:
            add_header("taskflow/taskflow.hpp")
            add_header("taskflow/algorithm/sort.hpp")

        if table.csv_reader_type:
            add_header("fmt/format.h")
            add_header("arrow/api.h")
            add_header("arrow/io/api.h")
            add_header("arrow/csv/api.h")

        if table.csv_writer_type:
            add_header("fmt/format.h")
            add_header("arrow/api.h")
            add_header("arrow/io/api.h")
            add_header("arrow/csv/api.h")
            add_header("arrow/ipc/writer.h")

    with open(output_file, "wt") as fobj:
        fobj.write("#pragma once\n")
        fobj.write("// This code is auto generated by cppsoa.\n")
        fobj.write("// Do not edit manually.\n\n")

        for header in headers:
            fobj.write(f"#include <{header}>\n")
        fobj.write("\n")

        fobj.write(f"namespace {spec.namespace} {{\n\n")

        for table in spec.tables:
            write_table(fobj, table)

        fobj.write(f"}} // namespace {spec.namespace}")
