#pragma once
// This code is auto generated by cppsoa.
// Do not edit manually.

#include <cstdint>
#include <vector>
#include <algorithm>
#include <taskflow/taskflow.hpp>
#include <taskflow/algorithm/for_each.hpp>
#include <taskflow/algorithm/sort.hpp>
#include <fmt/format.h>
#include <arrow/api.h>
#include <arrow/io/api.h>
#include <arrow/csv/api.h>
#include <arrow/ipc/writer.h>

namespace test {

struct ActivityTable {
    using size_type = std::size_t;
    using difference_type = std::ptrdiff_t;

    std::vector<std::uint64_t> pid{};
    std::vector<std::uint64_t> lid{};
    std::vector<std::int64_t> start_time{};
    std::vector<std::int32_t> duration{};
    std::vector<std::int16_t> activity_type{};

    struct Row {
        std::uint64_t pid{};
        std::uint64_t lid{};
        std::int64_t start_time{};
        std::int32_t duration{};
        std::int16_t activity_type{};
    };

    struct reference {
        ActivityTable* _c{nullptr};
        size_type _i{0};

        std::uint64_t& pid() {
            return _c->pid[_i];
        }
        std::uint64_t& lid() {
            return _c->lid[_i];
        }
        std::int64_t& start_time() {
            return _c->start_time[_i];
        }
        std::int32_t& duration() {
            return _c->duration[_i];
        }
        std::int16_t& activity_type() {
            return _c->activity_type[_i];
        }

        const std::uint64_t& pid() const {
            return _c->pid[_i];
        }
        const std::uint64_t& lid() const {
            return _c->lid[_i];
        }
        const std::int64_t& start_time() const {
            return _c->start_time[_i];
        }
        const std::int32_t& duration() const {
            return _c->duration[_i];
        }
        const std::int16_t& activity_type() const {
            return _c->activity_type[_i];
        }

        operator Row() const {
            return {
                 _c->pid[_i]
                ,  _c->lid[_i]
                ,  _c->start_time[_i]
                ,  _c->duration[_i]
                ,  _c->activity_type[_i]
            };
        }

        reference& operator=(const Row& value) {
            _c->pid[_i] = value.pid;
            _c->lid[_i] = value.lid;
            _c->start_time[_i] = value.start_time;
            _c->duration[_i] = value.duration;
            _c->activity_type[_i] = value.activity_type;
            return *this;
        }
    };

    struct const_reference {
        const ActivityTable* _c{nullptr};
        size_type _i{0};

        const std::uint64_t& pid() const {
            return _c->pid[_i];
        }
        const std::uint64_t& lid() const {
            return _c->lid[_i];
        }
        const std::int64_t& start_time() const {
            return _c->start_time[_i];
        }
        const std::int32_t& duration() const {
            return _c->duration[_i];
        }
        const std::int16_t& activity_type() const {
            return _c->activity_type[_i];
        }

        operator Row() const {
            return {
                 _c->pid[_i]
                ,  _c->lid[_i]
                ,  _c->start_time[_i]
                ,  _c->duration[_i]
                ,  _c->activity_type[_i]
            };
        }
    };

    void clear() {
        pid.clear();
        lid.clear();
        start_time.clear();
        duration.clear();
        activity_type.clear();
    }

    void reserve(size_type new_cap) {
        pid.reserve(new_cap);
        lid.reserve(new_cap);
        start_time.reserve(new_cap);
        duration.reserve(new_cap);
        activity_type.reserve(new_cap);
    }

    void shrink_to_fit() {
        pid.shrink_to_fit();
        lid.shrink_to_fit();
        start_time.shrink_to_fit();
        duration.shrink_to_fit();
        activity_type.shrink_to_fit();
    }

    void push_back(
            const std::uint64_t& pid
            , const std::uint64_t& lid
            , const std::int64_t& start_time
            , const std::int32_t& duration
            , const std::int16_t& activity_type
) {
        this->pid.push_back(pid);
        this->lid.push_back(lid);
        this->start_time.push_back(start_time);
        this->duration.push_back(duration);
        this->activity_type.push_back(activity_type);
    }

    void push_back(const Row& value) {
        this->pid.push_back(value.pid);
        this->lid.push_back(value.lid);
        this->start_time.push_back(value.start_time);
        this->duration.push_back(value.duration);
        this->activity_type.push_back(value.activity_type);
    }

    void resize(size_type count) {
        pid.resize(count);
        lid.resize(count);
        start_time.resize(count);
        duration.resize(count);
        activity_type.resize(count);
    }

    template <typename Functor>
    void for_each(Functor&& fn) {
        for (size_type _i = 0; _i < size(); _i++) {
            fn(reference{this, _i});
        }
    }

    template <typename Functor>
    void for_each(Functor&& fn) const {
        for (size_type _i = 0; _i < size(); _i++) {
            fn(const_reference{this, _i});
        }
    }


    template <typename Compare>
    void sort(Compare&& compare) {
        std::vector<size_type> _indexes(size());

        for (size_type _i = 0; _i < size(); _i++) {
            _indexes[_i] = _i;
        }

        std::sort(
            _indexes.begin(), _indexes.end(),
            [&](size_type _i, size_type _j) {
                return compare(reference{this, _i}, reference{this, _j});
            }
        );

        {
            std::vector<std::uint64_t> pid_new(size());
            for (size_type _i = 0; _i < size(); _i++) {
                pid_new[_i] = pid[_indexes[_i]];
            }
            pid = std::move(pid_new);
        }

        {
            std::vector<std::uint64_t> lid_new(size());
            for (size_type _i = 0; _i < size(); _i++) {
                lid_new[_i] = lid[_indexes[_i]];
            }
            lid = std::move(lid_new);
        }

        {
            std::vector<std::int64_t> start_time_new(size());
            for (size_type _i = 0; _i < size(); _i++) {
                start_time_new[_i] = start_time[_indexes[_i]];
            }
            start_time = std::move(start_time_new);
        }

        {
            std::vector<std::int32_t> duration_new(size());
            for (size_type _i = 0; _i < size(); _i++) {
                duration_new[_i] = duration[_indexes[_i]];
            }
            duration = std::move(duration_new);
        }

        {
            std::vector<std::int16_t> activity_type_new(size());
            for (size_type _i = 0; _i < size(); _i++) {
                activity_type_new[_i] = activity_type[_indexes[_i]];
            }
            activity_type = std::move(activity_type_new);
        }

    }

    template <typename Compare>
    void par_sort(tf::Executor& executor, Compare&& compare) {
        tf::Taskflow taskflow{};
        tf::IndexRange<size_type> _range(0, size(), 1);

        std::vector<size_type> _indexes(size());

        tf::Task build_index = taskflow.for_each_by_index(
            _range,
            [&](tf::IndexRange<size_type> _subrange) {
                for (size_type _i = _subrange.begin(); _i < _subrange.end(); _i += _subrange.step_size()) {
                    _indexes[_i] = _i;
                }
            }
        );

        tf::Task sort_index = taskflow.sort(
            _indexes.begin(), _indexes.end(),
            [&](size_type _i, size_type _j) {
                return compare(reference{this, _i}, reference{this, _j});
            }
        );
        sort_index.succeed(build_index);

        tf::Task update_pid = taskflow.emplace([&]{
            tf::Taskflow subflow{};
            std::vector<std::uint64_t> pid_new(size());
            subflow.for_each_by_index(
                _range,
                [&](tf::IndexRange<size_type> _subrange) {
                    for (size_type _i = _subrange.begin(); _i < _subrange.end(); _i += _subrange.step_size()) {
                        pid_new[_i] = pid[_indexes[_i]];
                    }
                }
            );
            executor.corun(subflow);
            pid = std::move(pid_new);
        });
        update_pid.succeed(sort_index);

        tf::Task update_lid = taskflow.emplace([&]{
            tf::Taskflow subflow{};
            std::vector<std::uint64_t> lid_new(size());
            subflow.for_each_by_index(
                _range,
                [&](tf::IndexRange<size_type> _subrange) {
                    for (size_type _i = _subrange.begin(); _i < _subrange.end(); _i += _subrange.step_size()) {
                        lid_new[_i] = lid[_indexes[_i]];
                    }
                }
            );
            executor.corun(subflow);
            lid = std::move(lid_new);
        });
        update_lid.succeed(sort_index);

        tf::Task update_start_time = taskflow.emplace([&]{
            tf::Taskflow subflow{};
            std::vector<std::int64_t> start_time_new(size());
            subflow.for_each_by_index(
                _range,
                [&](tf::IndexRange<size_type> _subrange) {
                    for (size_type _i = _subrange.begin(); _i < _subrange.end(); _i += _subrange.step_size()) {
                        start_time_new[_i] = start_time[_indexes[_i]];
                    }
                }
            );
            executor.corun(subflow);
            start_time = std::move(start_time_new);
        });
        update_start_time.succeed(sort_index);

        tf::Task update_duration = taskflow.emplace([&]{
            tf::Taskflow subflow{};
            std::vector<std::int32_t> duration_new(size());
            subflow.for_each_by_index(
                _range,
                [&](tf::IndexRange<size_type> _subrange) {
                    for (size_type _i = _subrange.begin(); _i < _subrange.end(); _i += _subrange.step_size()) {
                        duration_new[_i] = duration[_indexes[_i]];
                    }
                }
            );
            executor.corun(subflow);
            duration = std::move(duration_new);
        });
        update_duration.succeed(sort_index);

        tf::Task update_activity_type = taskflow.emplace([&]{
            tf::Taskflow subflow{};
            std::vector<std::int16_t> activity_type_new(size());
            subflow.for_each_by_index(
                _range,
                [&](tf::IndexRange<size_type> _subrange) {
                    for (size_type _i = _subrange.begin(); _i < _subrange.end(); _i += _subrange.step_size()) {
                        activity_type_new[_i] = activity_type[_indexes[_i]];
                    }
                }
            );
            executor.corun(subflow);
            activity_type = std::move(activity_type_new);
        });
        update_activity_type.succeed(sort_index);


        executor.run(taskflow).wait();
    }

    [[nodiscard]] reference operator[](size_type i) {
        return {this, i};
    }

    [[nodiscard]] const_reference operator[](size_type i) const {
        return {this, i};
    }

    [[nodiscard]] size_type size() const {
        return pid.size();
    }
};

class ActivityTableCsvReader {
  public:
    static constexpr std::int32_t default_block_size = 128 * 1 << 20;

    ActivityTableCsvReader() = delete;

    explicit ActivityTableCsvReader(const std::string& fname, bool use_threads = false,
                                   std::int32_t block_size = default_block_size)
        : file_name(fname)
        , input_file{}
        , reader{} {
        auto io_context = arrow::io::default_io_context();
        auto memory_pool = arrow::default_memory_pool();

        {
            auto result = arrow::io::ReadableFile::Open(file_name, memory_pool);
            if (!result.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to open file: {}: {}", file_name, result.status().ToString()));
            }
            input_file = result.MoveValueUnsafe();
        }

        auto read_options = arrow::csv::ReadOptions::Defaults();
        auto parse_options = arrow::csv::ParseOptions::Defaults();
        auto convert_options = arrow::csv::ConvertOptions::Defaults();

        read_options.use_threads = use_threads;
        read_options.block_size = block_size;

        convert_options.null_values = {};
        convert_options.strings_can_be_null = false;
        convert_options.quoted_strings_can_be_null = false;

        convert_options.include_columns = {
             "pid"
            ,  "lid"
            ,  "start_time"
            ,  "duration"
            ,  "activity_type"
        };
        convert_options.column_types = {
             { "pid", arrow::uint64() }
            ,  { "lid", arrow::uint64() }
            ,  { "start_time", arrow::int64() }
            ,  { "duration", arrow::int32() }
            ,  { "activity_type", arrow::int16() }
        };

        {
            auto result =
                arrow::csv::StreamingReader::Make(io_context, input_file, read_options, parse_options, convert_options);
            if (!result.ok()) [[unlikely]] {
                throw std::runtime_error(fmt::format("Arrow error: failed to create streaming reader: {}: {}",
                                                     file_name, result.status().ToString()));
            }
            reader = result.MoveValueUnsafe();
        }
    }

    ActivityTableCsvReader(ActivityTableCsvReader&) = delete;
    ActivityTableCsvReader(ActivityTableCsvReader&&) = delete;

    ActivityTableCsvReader& operator=(ActivityTableCsvReader&) = delete;
    ActivityTableCsvReader& operator=(ActivityTableCsvReader&&) = delete;

    [[nodiscard]] bool read_batch(ActivityTable& table) {
        std::shared_ptr<arrow::RecordBatch> batch{};
        {
            arrow::Status status = reader->ReadNext(&batch);
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to read batch: {}: {}", file_name, status.ToString()));
            }
        }

        if (!batch) {
            return false;
        }

        const std::size_t num_rows = batch->num_rows();
        table.reserve(table.size() + num_rows);

        auto pid_array = std::dynamic_pointer_cast<arrow::UInt64Array>(batch->GetColumnByName("pid"));
        if (pid_array->null_count() > 0) [[unlikely]] {
            throw std::runtime_error(fmt::format("Column 'pid' in file '{}' contains null values", file_name));
        }
        auto pid_values = pid_array->raw_values();

        auto lid_array = std::dynamic_pointer_cast<arrow::UInt64Array>(batch->GetColumnByName("lid"));
        if (lid_array->null_count() > 0) [[unlikely]] {
            throw std::runtime_error(fmt::format("Column 'lid' in file '{}' contains null values", file_name));
        }
        auto lid_values = lid_array->raw_values();

        auto start_time_array = std::dynamic_pointer_cast<arrow::Int64Array>(batch->GetColumnByName("start_time"));
        if (start_time_array->null_count() > 0) [[unlikely]] {
            throw std::runtime_error(fmt::format("Column 'start_time' in file '{}' contains null values", file_name));
        }
        auto start_time_values = start_time_array->raw_values();

        auto duration_array = std::dynamic_pointer_cast<arrow::Int32Array>(batch->GetColumnByName("duration"));
        if (duration_array->null_count() > 0) [[unlikely]] {
            throw std::runtime_error(fmt::format("Column 'duration' in file '{}' contains null values", file_name));
        }
        auto duration_values = duration_array->raw_values();

        auto activity_type_array = std::dynamic_pointer_cast<arrow::Int16Array>(batch->GetColumnByName("activity_type"));
        if (activity_type_array->null_count() > 0) [[unlikely]] {
            throw std::runtime_error(fmt::format("Column 'activity_type' in file '{}' contains null values", file_name));
        }
        auto activity_type_values = activity_type_array->raw_values();


        table.pid.insert(table.pid.end(), pid_values, pid_values + num_rows);
        table.lid.insert(table.lid.end(), lid_values, lid_values + num_rows);
        table.start_time.insert(table.start_time.end(), start_time_values, start_time_values + num_rows);
        table.duration.insert(table.duration.end(), duration_values, duration_values + num_rows);
        table.activity_type.insert(table.activity_type.end(), activity_type_values, activity_type_values + num_rows);

        return true;
    }

    void close() {
        {
            auto status = reader->Close();
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to close reader: {}: {}", file_name, status.ToString()));
            }
        }

        {
            auto status = input_file->Close();
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to close input file: {}: {}", file_name, status.ToString()));
            }
        }
    }

  private:
    std::string file_name{};
    std::shared_ptr<arrow::io::ReadableFile> input_file{};
    std::shared_ptr<arrow::csv::StreamingReader> reader{};
};

class ActivityTableCsvWriter {
  public:
    static constexpr std::int32_t default_batch_size = 1 << 20;

    ActivityTableCsvWriter() = delete;

    ActivityTableCsvWriter(const std::string& fname, std::int32_t batch_size = default_batch_size)
        : file_name(fname)
        , schema{}
        , output_file{}
        , writer{} {
        schema = arrow::schema({
             arrow::field("pid", arrow::uint64())
            ,  arrow::field("lid", arrow::uint64())
            ,  arrow::field("start_time", arrow::int64())
            ,  arrow::field("duration", arrow::int32())
            ,  arrow::field("activity_type", arrow::int16())
        });

        auto write_options = arrow::csv::WriteOptions::Defaults();
        write_options.include_header = true;
        write_options.batch_size = batch_size;

        {
            auto result = arrow::io::FileOutputStream::Open(file_name);
            if (!result.ok()) [[unlikely]] {
                throw std::runtime_error(fmt::format("Arrow error: failed to open file: {}: {}", file_name,
                                                     result.status().ToString()));
            }
            output_file = result.MoveValueUnsafe();
        }

        {
            auto result = arrow::csv::MakeCSVWriter(output_file, schema, write_options);
            if (!result.ok()) [[unlikely]] {
                throw std::runtime_error(fmt::format("Arrow error: failed to create writer: {}: {}",
                                                     file_name, result.status().ToString()));
            }
            writer = result.MoveValueUnsafe();
        }
    }

    ActivityTableCsvWriter(ActivityTableCsvWriter&) = delete;
    ActivityTableCsvWriter(ActivityTableCsvWriter&&) = delete;

    ActivityTableCsvWriter& operator=(ActivityTableCsvWriter&) = delete;
    ActivityTableCsvWriter& operator=(ActivityTableCsvWriter&&) = delete;

    [[nodiscard]] std::shared_ptr<arrow::RecordBatch> build_batch(const ActivityTable& table) {
        arrow::UInt64Builder pid_builder{};
        {
            auto status = pid_builder.Reserve(table.size());
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to reserve builder memory for 'pid' {}: {}", file_name, status.ToString()));
            }
        }
        {
            auto status = pid_builder.AppendValues(table.pid);
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to append values for 'pid' {}: {}", file_name, status.ToString()));
            }
        }

        arrow::UInt64Builder lid_builder{};
        {
            auto status = lid_builder.Reserve(table.size());
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to reserve builder memory for 'lid' {}: {}", file_name, status.ToString()));
            }
        }
        {
            auto status = lid_builder.AppendValues(table.lid);
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to append values for 'lid' {}: {}", file_name, status.ToString()));
            }
        }

        arrow::Int64Builder start_time_builder{};
        {
            auto status = start_time_builder.Reserve(table.size());
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to reserve builder memory for 'start_time' {}: {}", file_name, status.ToString()));
            }
        }
        {
            auto status = start_time_builder.AppendValues(table.start_time);
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to append values for 'start_time' {}: {}", file_name, status.ToString()));
            }
        }

        arrow::Int32Builder duration_builder{};
        {
            auto status = duration_builder.Reserve(table.size());
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to reserve builder memory for 'duration' {}: {}", file_name, status.ToString()));
            }
        }
        {
            auto status = duration_builder.AppendValues(table.duration);
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to append values for 'duration' {}: {}", file_name, status.ToString()));
            }
        }

        arrow::Int16Builder activity_type_builder{};
        {
            auto status = activity_type_builder.Reserve(table.size());
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to reserve builder memory for 'activity_type' {}: {}", file_name, status.ToString()));
            }
        }
        {
            auto status = activity_type_builder.AppendValues(table.activity_type);
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to append values for 'activity_type' {}: {}", file_name, status.ToString()));
            }
        }


        std::shared_ptr<arrow::Array> pid_array{};
        {
            auto status = pid_builder.Finish(&pid_array);
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to finish builder for 'pid' {}: {}", file_name, status.ToString()));
            }
        }

        std::shared_ptr<arrow::Array> lid_array{};
        {
            auto status = lid_builder.Finish(&lid_array);
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to finish builder for 'lid' {}: {}", file_name, status.ToString()));
            }
        }

        std::shared_ptr<arrow::Array> start_time_array{};
        {
            auto status = start_time_builder.Finish(&start_time_array);
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to finish builder for 'start_time' {}: {}", file_name, status.ToString()));
            }
        }

        std::shared_ptr<arrow::Array> duration_array{};
        {
            auto status = duration_builder.Finish(&duration_array);
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to finish builder for 'duration' {}: {}", file_name, status.ToString()));
            }
        }

        std::shared_ptr<arrow::Array> activity_type_array{};
        {
            auto status = activity_type_builder.Finish(&activity_type_array);
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to finish builder for 'activity_type' {}: {}", file_name, status.ToString()));
            }
        }


        return arrow::RecordBatch::Make(
            schema,
            table.size(),
            {
                 pid_array
                ,  lid_array
                ,  start_time_array
                ,  duration_array
                ,  activity_type_array
            }
        );
    }

    void write_batch(std::shared_ptr<arrow::RecordBatch>& batch) {
        auto status = writer->WriteRecordBatch(*batch);
        if (!status.ok()) [[unlikely]] {
            throw std::runtime_error(
                fmt::format("Arrow error: failed to write batch {}: {}", file_name, status.ToString()));
        }
    }

    void close() {
        {
            auto status = writer->Close();
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to close writer: {}: {}", file_name, status.ToString()));
            }
        }

        {
            auto status = output_file->Close();
            if (!status.ok()) [[unlikely]] {
                throw std::runtime_error(
                    fmt::format("Arrow error: failed to close output file: {}: {}", file_name, status.ToString()));
            }
        }
    }

  private:
    std::string file_name{};
    std::shared_ptr<arrow::Schema> schema{};
    std::shared_ptr<arrow::io::FileOutputStream> output_file{};
    std::shared_ptr<arrow::ipc::RecordBatchWriter> writer{};
};

} // namespace test